<?php
$projects = [
    [
        'title' => 'Personal Finances website',
        'url' => 'https://controle-financeiro.rafaellotto.com.br',
        'launched_at' => 'January/2024',
        'tags' => ['Laravel', 'Filament', 'Livewire', 'Alpine.js'],
    ],
    [
        'title' => 'Gold Virtual Airlines Core API',
        'url' => 'https://core.goldvirtual.com.br',
        'launched_at' => 'January/2024',
        'tags' => ['Laravel'],
    ],
    [
        'title' => 'Gold Virtual Airlines Jobs website and API',
        'url' => 'https://jobs.goldvirtual.com.br',
        'launched_at' => 'August/2023',
        'tags' => ['Laravel'],
    ],
    [
        'title' => 'RTM Brasil CHUG certificates generator website',
        'url' => 'https://certificados-chug.rtmbrasil.org.br/',
        'launched_at' => 'August/2023',
        'tags' => ['Laravel'],
    ],
    [
        'title' => 'IBASP\'s prayer request website',
        'url' => 'https://intercessao.ibasp.org.br/',
        'launched_at' => 'May/2023',
        'tags' => ['Laravel'],
    ],
    [
        'title' => 'R&S Honorato Contabilidade\'s website',
        'url' => 'https://www.contabilhonorato.com.br',
        'launched_at' => 'September/2022',
        'tags' => ['Bootstrap CSS'],
    ],
    [
        'title' => 'RTM Brasil\'s VIP meeting website',
        'url' => null,
        'launched_at' => 'July/2022',
        'tags' => ['Laravel', 'Vue.js'],
    ],
    [
        'title' => 'RTM Brasil\'s iOS App',
        'url' => 'https://apps.apple.com/us/app/r%C3%A1dio-trans-mundial/id690921653?platform=iphone',
        'launched_at' => 'February/2022',
        'tags' => ['Flutter'],
    ],
    [
        'title' => 'RTM Brasil\'s Android App',
        'url' => 'https://play.google.com/store/apps/details?id=com.rtm.transmundial',
        'launched_at' => 'February/2022',
        'tags' => ['Flutter'],
    ],
    [
        'title' => 'RTM Brasil\'s donation website',
        'url' => 'https://doe.rtmbrasil.org.br',
        'launched_at' => 'January/2022',
        'tags' => ['Laravel'],
    ],
    [
        'title' => 'FoolishLife\'s website',
        'url' => 'https://www.foolishlife.org/',
        'launched_at' => 'January/2022',
        'tags' => ['Bootstrap CSS', 'Laravel'],
    ],
    [
        'title' => 'IBASP\'s voting website',
        'url' => 'https://eleicoes.ibasp.org.br/',
        'launched_at' => 'January/2022',
        'tags' => ['Bootstrap CSS', 'Laravel'],
    ],
    [
        'title' => 'IBASP\'s iOS App to read the Bible',
        'url' => 'https://apps.apple.com/us/app/leitura-b%C3%ADblica-ibasp/id1602779648',
        'launched_at' => 'January/2022',
        'tags' => ['Flutter'],
    ],
    [
        'title' => 'IBASP\'s Android App to read the Bible',
        'url' => 'https://play.google.com/store/apps/details?id=br.org.ibasp.leitura',
        'launched_at' => 'December/2021',
        'tags' => ['Flutter'],
    ],
    [
        'title' => 'Rádio Boas Novas\' iOS App',
        'url' => 'https://apps.apple.com/tj/app/r%C3%A1dio-boas-novas-fm/id1584654133?platform=iphone',
        'launched_at' => 'September/2021',
        'tags' => ['Flutter'],
    ],
    [
        'title' => 'Rádio Boas Novas\' Android App',
        'url' => 'https://play.google.com/store/apps/details?id=br.com.agenciauny.radioboasnovasam',
        'launched_at' => 'August/2021',
        'tags' => ['Flutter'],
    ],
    [
        'title' => 'Animal\'s sounds iOS App for my son',
        'url' => 'https://apps.apple.com/us/app/sons-dos-animais-by-fit/id1573619121?platform=iphone',
        'launched_at' => 'August/2021',
        'tags' => ['Flutter'],
    ],
    [
        'title' => 'Animal\'s sounds Android App for my son',
        'url' => 'https://play.google.com/store/apps/details?id=br.app.dofit.animals_sounds',
        'launched_at' => 'June/2021',
        'tags' => ['Flutter'],
    ],
    [
        'title' => 'IBASP\'s library website',
        'url' => 'https://biblioteca.ibasp.org.br/',
        'launched_at' => 'May/2021',
        'tags' => ['Bootstrap CSS', 'Laravel'],
    ],
    [
        'title' => 'IBASP\'s administration website',
        'url' => null,
        'launched_at' => 'February/2021',
        'tags' => ['Bootstrap CSS', 'Laravel'],
    ],
    [
        'title' => 'RTM Brasil\'s website',
        'url' => 'https://www.rtmbrasil.org.br/',
        'launched_at' => 'February/2021',
        'tags' => ['Next.js', 'React', 'Tailwind CSS'],
    ],
    [
        'title' => 'RTM Brasil\'s administration website',
        'url' => null,
        'launched_at' => 'January/2021',
        'tags' => ['Laravel', 'Tailwind CSS'],
    ],
    [
        'title' => 'Defatto Contábil client\'s website',
        'url' => 'https://clientes.defattocontabil.com.br/',
        'launched_at' => 'January/2021',
        'tags' => ['Laravel', 'Tailwind CSS'],
    ],
    [
        'title' => 'Defatto Contábil\'s website',
        'url' => 'https://defattocontabil.com.br/',
        'launched_at' => 'November/2020',
        'tags' => ['Bootstrap CSS'],
    ],
    [
        'title' => 'RTM Brasil\'s inventory website',
        'url' => null,
        'launched_at' => 'September/2020',
        'tags' => ['Bootstrap CSS', 'CodeIgniter', 'Laravel'],
    ],
    [
        'title' => 'RTM Portugal\'s Bible Courses website',
        'url' => 'https://academia.rtmportugal.org/',
        'launched_at' => 'August/2020',
        'tags' => ['Bootstrap CSS', 'CodeIgniter'],
    ],
    [
        'title' => 'RTM Brasil\'s Bible Courses website',
        'url' => 'https://cursos.rtmbrasil.org.br/',
        'launched_at' => 'July/2020',
        'tags' => ['Bootstrap CSS', 'CodeIgniter', 'Laravel'],
    ],
    [
        'title' => 'IBASP\'s treasury website',
        'url' => null,
        'launched_at' => 'January/2020',
        'tags' => ['Bootstrap CSS', 'CodeIgniter', 'Laravel'],
    ],
    [
        'title' => 'RTM Brasil\'s Presente Diário PWA',
        'url' => 'https://presentediario.rtmbrasil.org.br/',
        'launched_at' => 'January/2020',
        'tags' => ['PWA'],
    ],
    [
        'title' => 'RTM Brasil\'s Timesheet website',
        'url' => 'https://timesheet.rtmbrasil.org.br/',
        'launched_at' => 'January/2020',
        'tags' => ['PHP'],
    ],
    [
        'title' => 'RTM Brasil\'s Presente Diário management website',
        'url' => null,
        'launched_at' => 'September/2019',
        'tags' => ['CodeIgniter', 'Laravel', 'Vue.js', 'Inertia.js'],
    ],
    [
        'title' => 'RTM Brasil\'s store website',
        'url' => 'https://loja.rtmbrasil.org.br/',
        'launched_at' => 'June/2019',
        'tags' => ['WordPress', 'WooCommerce'],
    ],
    [
        'title' => 'RTM Brasil CHUG verses website',
        'url' => 'https://versiculos-chug.rtmbrasil.org.br/',
        'launched_at' => 'May/2019',
        'tags' => ['PWA'],
    ],
    [
        'title' => 'Kindergarten Hänsel und Gretel\'s website',
        'url' => 'https://www.kindergartenhanselgretel.com.br/',
        'launched_at' => 'March/2019',
        'tags' => ['Materialize CSS', 'WordPress'],
    ],
    [
        'title' => 'IBASP\'s website',
        'url' => 'https://www.ibasp.org.br/',
        'launched_at' => 'August/2018',
        'tags' => ['Bootstrap CSS', 'WordPress'],
    ],
];